# Generated by Django 4.2 on 2024-01-21 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adress', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('approximity_surface', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NeedElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='BesoinsIcons/')),
                ('elements', models.ManyToManyField(related_name='exemples', to='archimatch_app.needelement')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ArchitectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='ArchitectTypeIcons/')),
                ('short_def', models.TextField(max_length=1000)),
                ('needs', models.ManyToManyField(related_name='architects', to='archimatch_app.need')),
            ],
        ),
        migrations.CreateModel(
            name='ArchitectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adress', models.CharField(blank=True, max_length=255, null=True)),
                ('arch_identifier', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('meeting_date', models.DateTimeField()),
                ('meeting_duration', models.IntegerField(default=30)),
                ('meeting_time', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('registration_number', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Refused', 'Refused'), ('En attente Demo', 'En attente Demo'), ('En attente Decision', 'En attente Decision')], max_length=255)),
                ('architect_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archimatch_app.architecttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Architect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adress', models.CharField(default='', max_length=255)),
                ('arch_identifier', models.CharField(default='', max_length=10)),
                ('bio', models.TextField(default='', max_length=1000)),
                ('company_name', models.CharField(default='', max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='CompanyLogos/')),
                ('first_cnx', models.BooleanField(default=False)),
                ('video_presentation', models.FileField(blank=True, null=True, upload_to='ArchitectVideos/')),
                ('arch_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architects', to='archimatch_app.architecttype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Architects',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('super_user', models.BooleanField(default=False)),
                ('rights', models.ManyToManyField(related_name='admins', to='archimatch_app.right')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Admins',
            },
        ),
    ]
