# Generated by Django 4.2 on 2024-03-18 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0002_announcement_needelement_right_need_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architectrequest',
            old_name='adress',
            new_name='adresse',
        ),
        migrations.AddField(
            model_name='need',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='need',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='needelement',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='needelement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
