# Generated by Django 4.2 on 2024-03-27 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0003_rename_adress_architectrequest_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedPieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nb_suite_parental', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('nb_cuisine', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('nb_Terasse', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('nb_chambre', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('nb_salle_a_manger', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('nb_jardin', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('nb_chambre_enfant', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('nb_salle_bain', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('nb_haul', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('nb_salon', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('nb_bureau', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('nb_garage', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='approximity_surface',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='type',
        ),
        migrations.AddField(
            model_name='announcement',
            name='adresse',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='architect_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='archimatch_app.architecttype'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='budget',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='categories',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='archimatch_app.client'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='details',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='extra',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='house_type',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='need',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='surface_terrain',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='surface_travaux',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='work_style',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='work_type',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='town',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('need', models.CharField(blank=True, default='need1', max_length=255, null=True)),
                ('town', models.CharField(blank=True, default='need1', max_length=255, null=True)),
                ('categories', models.CharField(blank=True, default='need1', max_length=255, null=True)),
                ('surface_terrain', models.CharField(blank=True, default='need1', max_length=255, null=True)),
                ('surface_travaux', models.CharField(blank=True, default='need1', max_length=255, null=True)),
                ('house_type', models.CharField(blank=True, default='need1', max_length=255, null=True)),
                ('work_type', models.CharField(blank=True, default='need1', max_length=255, null=True)),
                ('budget', models.CharField(blank=True, default='need1', max_length=255, null=True)),
                ('details', models.CharField(blank=True, default='need1', max_length=255, null=True)),
                ('work_style', models.CharField(blank=True, default='need1', max_length=255, null=True)),
                ('extra', models.CharField(blank=True, default='need1', max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, default='need1', max_length=255, null=True)),
                ('architect_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='archimatch_app.architecttype')),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='archimatch_app.client')),
                ('need_pieces', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='archimatch_app.needpieces')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='need_pieces',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='archimatch_app.needpieces'),
        ),
    ]
