# Generated by Django 4.2 on 2024-03-27 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0004_needpieces_remove_announcement_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='architect_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archimatch_app.architecttype'),
        ),
    ]
