# Generated by Django 4.2 on 2024-04-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0005_alter_announcement_architect_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architectrequest',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Refused', 'Refused'), ('En attente Demo', 'En attente Demo'), ('En attente Decision', 'En attente Decision')], default=('En attente Decision', 'En attente Decision'), max_length=255),
        ),
    ]
