# Generated by Django 4.2 on 2024-04-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0006_alter_architectrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='categories',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='architect',
            name='complexity',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='architect',
            name='house_type',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='architect',
            name='work_style',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='architect',
            name='work_type',
            field=models.CharField(blank=True, default='need1', max_length=255, null=True),
        ),
    ]
