# Generated by Django 5.0.1 on 2024-04-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0008_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='Description',
            field=models.TextField(),
        ),
    ]
