# Generated by Django 5.0.1 on 2024-04-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0009_alter_subscription_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='Sub_type',
            new_name='Sub_name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='Description',
        ),
        migrations.AddField(
            model_name='subscription',
            name='Satus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='option1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='option2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='option3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='option4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='option5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='option6',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='End_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Token_num',
            field=models.IntegerField(),
        ),
    ]
