# Generated by Django 5.0.1 on 2024-04-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0010_rename_sub_type_subscription_sub_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='End_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='Satus',
            new_name='satus',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='Start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='Sub_name',
            new_name='sub_name',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='Token_num',
            new_name='token_num',
        ),
    ]
