# Generated by Django 5.0.1 on 2024-04-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0012_rename_option2_subscription_archi_supp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='token_num',
            field=models.IntegerField(max_length=2),
        ),
    ]
