# Generated by Django 5.0.1 on 2024-04-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0014_alter_subscription_token_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='satus',
            new_name='active',
        ),
    ]
