# Generated by Django 5.0.1 on 2024-04-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0015_rename_satus_subscription_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='proj_exposition',
            new_name='mev_profil',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='prop_project',
            new_name='prop_selon_pref',
        ),
    ]
