# Generated by Django 5.0.1 on 2024-04-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0016_rename_proj_exposition_subscription_mev_profil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
    ]
