# Generated by Django 5.0.1 on 2024-04-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0018_subscriptionsrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionsRequest',
            new_name='SubscriptionRequest',
        ),
    ]
