# Generated by Django 5.0.1 on 2024-04-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0019_rename_subscriptionsrequest_subscriptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='sub_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
