# Generated by Django 5.0.1 on 2024-04-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0020_architect_sub_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='registration_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
