# Generated by Django 5.0.1 on 2024-04-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0021_architect_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiServicetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='architect',
            name='services',
            field=models.ManyToManyField(related_name='architects', to='archimatch_app.archiservicetype'),
        ),
    ]
