# Generated by Django 5.0.1 on 2024-04-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0022_archiservicetype_architect_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='company_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
