# Generated by Django 5.0.1 on 2024-04-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0023_alter_architect_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='adress',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='architect',
            name='arch_identifier',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='architect',
            name='bio',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='architect',
            name='registration_number',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='architect',
            name='sub_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
