# Generated by Django 5.0.1 on 2024-04-22 09:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0024_alter_architect_adress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_name', models.CharField(max_length=255)),
                ('free_tokens', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)])),
                ('price', models.FloatField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='architect',
            name='sub_name',
        ),
        migrations.AddField(
            model_name='architect',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='archimatch_app.archisubscription'),
        ),
    ]
