# Generated by Django 5.0.1 on 2024-04-22 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0037_alter_architect_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archisubscription',
            name='free_tokens',
            field=models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='archisubscription',
            name='price',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='archisubscription',
            name='sub_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
