# Generated by Django 5.0.1 on 2024-04-22 11:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0038_alter_archisubscription_free_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archisubscription',
            name='free_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='archisubscription',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='architect',
            name='subscription',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='archimatch_app.archisubscription'),
        ),
    ]
