# Generated by Django 5.0.1 on 2024-04-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0041_bankcard_alter_architect_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='devi_gen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='fournisseur',
            field=models.BooleanField(default=False),
        ),
    ]
