# Generated by Django 5.0.1 on 2024-04-25 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0044_remove_preference_arch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=255)),
                ('date_of_transaction', models.DateField()),
                ('sub_purchased', models.CharField(max_length=255)),
                ('amount_paid', models.FloatField()),
                ('architect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archimatch_app.architect')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
