# Generated by Django 4.2 on 2024-04-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0048_alter_realizationimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizationimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='realizations/'),
        ),
    ]
