# Generated by Django 4.2 on 2024-05-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0049_alter_realizationimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='realization',
            name='project_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
