# Generated by Django 5.0.1 on 2024-05-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0051_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='architect_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='ArchitectsAvatars/'),
        ),
    ]
