# Generated by Django 5.0.1 on 2024-05-11 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0053_devis_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='architect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='archimatch_app.architect'),
        ),
    ]
