# Generated by Django 5.0.1 on 2024-05-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0054_alter_selection_architect'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='selection_count',
            field=models.IntegerField(default=0),
        ),
    ]
