# Generated by Django 5.0.1 on 2024-05-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0059_alter_realization_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
