# Generated by Django 5.0.1 on 2024-05-26 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0060_selection_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Reports', to='archimatch_app.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchiReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=255)),
                ('rep_count', models.IntegerField(default=0)),
                ('architect', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Archireports', to='archimatch_app.architect')),
                ('reports', models.ManyToManyField(related_name='Arhcireports', to='archimatch_app.report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
