# Generated by Django 5.0.1 on 2024-05-26 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0062_remove_report_client_alter_archireport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.OneToOneField(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
