# Generated by Django 5.0.1 on 2024-05-27 09:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0063_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Non-traité', max_length=255)),
                ('rep_count', models.IntegerField(default=0)),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Clientreport', to='archimatch_app.client')),
                ('reports', models.ManyToManyField(related_name='Clientreport', to='archimatch_app.report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
