# Generated by Django 4.2 on 2024-05-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0065_architect_shared_architect_tokens_architect_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='architect',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='devis',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='announcement',
            name='architect_found',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devis',
            name='architect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis_architect', to='archimatch_app.architect'),
        ),
    ]
