# Generated by Django 4.2 on 2024-05-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0066_remove_selection_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='announcement',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='archimatch_app.announcement'),
        ),
        migrations.AddField(
            model_name='selection',
            name='architect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='archimatch_app.architect'),
        ),
        migrations.AddField(
            model_name='selection',
            name='devis',
            field=models.ManyToManyField(related_name='Selections', to='archimatch_app.devis'),
        ),
        migrations.AddField(
            model_name='selection',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='interested_architects',
            field=models.ManyToManyField(blank=True, related_name='interested_architects', to='archimatch_app.architect'),
        ),
    ]
