# Generated by Django 4.2 on 2024-05-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0067_selection_announcement_selection_architect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='announcement',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='archimatch_app.announcement'),
        ),
    ]
