# Generated by Django 4.2 on 2024-05-27 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0068_alter_selection_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='archimatch_app.announcement'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='architect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='archimatch_app.architect'),
        ),
    ]
