# Generated by Django 4.2 on 2024-05-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0069_alter_selection_announcement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='rights',
            field=models.ManyToManyField(blank=True, null=True, related_name='admins', to='archimatch_app.right'),
        ),
    ]
