# Generated by Django 4.2 on 2024-05-27 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0070_alter_admin_rights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='announcement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='archimatch_app.announcement'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='architect',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='archimatch_app.architect'),
        ),
    ]
