# Generated by Django 4.2 on 2024-05-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0072_alter_selection_announcement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='card_holder',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
