# Generated by Django 4.2 on 2024-05-28 12:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0075_alter_report_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Non-traité', max_length=255)),
                ('rep_count', models.IntegerField(default=0)),
                ('comment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commet_report', to='archimatch_app.comment')),
                ('reports', models.ManyToManyField(related_name='comments_report', to='archimatch_app.report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
