# Generated by Django 4.2 on 2024-05-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimatch_app', '0078_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='chosen_spec',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archimatchuser',
            name='user_type',
            field=models.CharField(choices=[('Architect', 'Architect'), ('Client', 'Client'), ('Admin', 'Admin'), ('Supplier', 'Supplier')], max_length=200),
        ),
    ]
